layout_spectrum: 0.5319149
typography_spectrum: 0.387234
color:
  saturation: 0.7575787
  lightness: 0.2390383
  brandStrength: 0.5191489
  brandColors:
    - '#000000'
    - '#0000FE'
    - '#FFFFFF'
    - '#9191FD'
    - '#383838'
  rhythmicContrast: 0.8942092
name: www.imtechnologiesllc.com
